#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

#&> /dev/null exec gnome-session

export GALLIUM_HUD=fps
export GALLIUM_HUD_VISIBLE=false
export GALLIUM_HUD_TOGGLE_SIGNAL=10
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

fcitx -D &
xrdb ~/.config/x11/Xresources &
xsetroot -cursor_name left_ptr &
setbg &
urxvtd &
sxhkd &
compton --backend=glx -b &
checkupdates_notify &
exec bspwm
