#!/usr/bin/zsh

bspc rule -a Firefox focus=off
bspc rule -a punes state=pseudo_tiled
bspc rule -a mednafen state=pseudo_tiled
bspc rule -a retroarch state=fullscreen

bspc config border_width 4
bspc config window_gap 16

bspc config pointer_action1 resize_corner
bspc config pointer_action3 move

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config click_to_focus true
bspc config initial_polarity second_child
bspc config external_rules_command "$(whence makerule)"
bspc config remove_disabled_monitors

bspc monitor -d I II III IV V VI VII VIII IX

bspc config focused_border_color '#717885'
bspc config presel_feedback_color '#717885'
bspc config normal_border_color  '#1a2948'
bspc config active_border_color   '#1a2948'
