#!/usr/bin/zsh

bspc config border_width 4
bspc config window_gap 20

bspc config pointer_action1 resize_corner
bspc config pointer_action3 move

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config click_to_focus true
bspc config initial_polarity second_child
bspc config external_rules_command "$(whence makerule)"
bspc config remove_disabled_monitors

bspc monitor -d I II III IV V VI VII VIII IX

bspc config normal_border_color  '#586e75'
bspc config focused_border_color '#6c71c4'
bspc config presel_feedback_color '#6c71c4'
bspc config active_border_color  '#6c71c4'
